//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentMaster
    {
        public int AssignId { get; set; }
        public string AssignmentDesc { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime AssignDate { get; set; }
        public string CandNames { get; set; }
    }
}
