//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchReportMaster
    {
        public int BRId { get; set; }
        public System.DateTime BRDate { get; set; }
        public System.TimeSpan BRTime { get; set; }
        public string TopicName { get; set; }
        public string TopicDescription { get; set; }
        public string SessionDetails { get; set; }
        public bool IsTaken { get; set; }
        public Nullable<int> refBatchId { get; set; }
    
        public virtual BatchMaster BatchMaster { get; set; }
    }
}
