//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateMaster()
        {
            this.CandBatchMasters = new HashSet<CandBatchMaster>();
        }
    
        public int CandId { get; set; }
        public string CandFullName { get; set; }
        public string CandMobileNumber { get; set; }
        public string CandEmailId { get; set; }
        public Nullable<int> CandStatus { get; set; }
        public bool IsCandEnabled { get; set; }
        public Nullable<int> refTechId { get; set; }
        public string remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandBatchMaster> CandBatchMasters { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual TechMaster TechMaster { get; set; }
    }
}
