//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandSupportMaster
    {
        public int CSId { get; set; }
        public string CSTopic { get; set; }
        public string CSGivenBy { get; set; }
        public System.DateTime CSDate { get; set; }
        public System.TimeSpan CSTime { get; set; }
        public bool IsCSIncentiveCal { get; set; }
        public string CSRemarks { get; set; }
    }
}
