//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandBatchMaster
    {
        public int CandBatchId { get; set; }
        public Nullable<int> refBatchId { get; set; }
        public Nullable<int> refCandId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime addDate { get; set; }
    
        public virtual BatchMaster BatchMaster { get; set; }
        public virtual CandidateMaster CandidateMaster { get; set; }
    }
}
