//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMRMEntities : DbContext
    {
        public dbMRMEntities()
            : base("name=dbMRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssignmentMaster> AssignmentMasters { get; set; }
        public virtual DbSet<BatchMaster> BatchMasters { get; set; }
        public virtual DbSet<BatchReportMaster> BatchReportMasters { get; set; }
        public virtual DbSet<CandBatchMaster> CandBatchMasters { get; set; }
        public virtual DbSet<CandidateMaster> CandidateMasters { get; set; }
        public virtual DbSet<CandSupportMaster> CandSupportMasters { get; set; }
        public virtual DbSet<GlobalNotesMaster> GlobalNotesMasters { get; set; }
        public virtual DbSet<JobDiscussMaster> JobDiscussMasters { get; set; }
        public virtual DbSet<MeetingMaster> MeetingMasters { get; set; }
        public virtual DbSet<ResumeUnderStandingMaster> ResumeUnderStandingMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<ScreeningMaster> ScreeningMasters { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<TechMaster> TechMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
