//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalNotesMaster
    {
        public int GlobalNoteId { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateOfNotes { get; set; }
        public System.TimeSpan TimeOfNotes { get; set; }
        public Nullable<int> WrittenBy { get; set; }
        public bool MakeHidden { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
