//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingMaster
    {
        public int MeetingId { get; set; }
        public string MeetingDescription { get; set; }
        public string Conclusion { get; set; }
        public System.DateTime MeetDate { get; set; }
        public System.TimeSpan MeetTime { get; set; }
        public Nullable<int> ArrangedBy { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
