//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeUnderStandingMaster
    {
        public int RUId { get; set; }
        public System.DateTime RUDate { get; set; }
        public System.TimeSpan RUTime { get; set; }
        public string CandName { get; set; }
        public string ResumeTitle { get; set; }
        public string RURemarks { get; set; }
        public bool IsRUIncentiveCal { get; set; }
    }
}
