//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTablesExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningMaster
    {
        public int ScreeningId { get; set; }
        public System.DateTime ScreeningDate { get; set; }
        public System.TimeSpan ScreeningTime { get; set; }
        public string CandName { get; set; }
        public string Technology { get; set; }
        public string AssignedBy { get; set; }
        public string SCRemarks { get; set; }
    }
}
